name: Publish docker images

on:
  # Trigger the workflow on push
  # but only for the master branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push docker images to GitHub Packages
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/bula21/mova21-smssender
      IMAGE_NAME: sms-sender

    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        id: meta
        name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=true
            type=ref,event=tag,enable=${{ github.event.ref_type == 'tag' }}
          flavor: |
            latest=false
      -
        name: Build docker
        id: build-docker
        uses: docker/build-push-action@v3
        with:
          target: smssender-deploy
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Push docker
        uses: docker/build-push-action@v3
        with:
          push: true
          target: smssender-deploy
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - 
        name: Deploy to Azure Web App
        uses: azure/webapps-deploy@016bdd3f9b7cec60310bcf9da98f671628795644
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ steps.meta.outputs.tags }}@${{ steps.build-docker.outputs.digest }}