name: Publish docker images

on:
  # Trigger the workflow on push
  # but only for the master branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push docker images to GitHub Packages
    runs-on: ubuntu-latest

    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=true
            type=ref,event=tag,enable=${{ github.event.ref_type == 'tag' }}
          flavor: |
            latest=false
            suffix=-${{ github.event.ref_type == 'tag' && "mova21-smssender" || format('{0}-development', "mova21-smssender") }},onlatest=true
      - 
        name: Build and push Docker image
        uses: docker/build-push-action@v3
        id: build-and-deploy
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - 
        name: Build docker
        uses: docker/build-push-action@v3
        with:
          target: smssender-deploy
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Push docker
        uses: docker/build-push-action@v3
        with:
          push: true
          target: smssender-deploy
          tags: |
            ghcr.io/bula21/mova21-smssender/smssender:latest
